### ISSUE TITLE
JSON output returned doesn't contain expected file path

### ISSUE THREAD

**Issue by Wenzel** [slimm609/checksec.sh#160]
## Issue

When running checksec on some binaries and expecting a JSON output, the output doesn't contain the file path key, but instead a `file` key.

## Debug Report
include the output of `checksec --debug_report`
~~~
***** Checksec debug *****
uid=1000(wenzel) gid=1000(wenzel) groups=1000(wenzel),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),118(lpadmin),129(sambashare),131(docker),132(libvirt)
Linux Strix 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
checksec version: 2.1.0 -- 2019072901
OS=Ubuntu
VER=20.04
-rwxr-xr-x 1 root root 43416 Sep  5  2019 /usr/bin/cat
/usr/bin/cat: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b357ed53c8c9cb1a312f83b28982304effae0135, for GNU/Linux 3.2.0, stripped
lrwxrwxrwx 1 root root 21 Sep 26  2019 /usr/bin/awk -> /etc/alternatives/awk
-rwxr-xr-x 1 root root 711136 Nov  3  2019 /usr/bin/gawk
/usr/bin/gawk: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b863ebf57d3cc33d8e7fed3be0e0b5d235489b46, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 30960 Feb 27 06:52 /usr/sbin/sysctl
/usr/sbin/sysctl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=45715ae45d98c92b22851f68d64df68a94d54364, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 39288 Sep  5  2019 /usr/bin/uname
/usr/bin/uname: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3354931bca4ff072b26258a956ffde08ead5f341, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47448 Sep  5  2019 /usr/bin/mktemp
/usr/bin/mktemp: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=cd6eaf6c3773543335f009051580413f0cdcd905, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 753336 Apr 20 13:53 /usr/bin/openssl
/usr/bin/openssl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=cbf09dca92335f43c77c9fff1e28ec9b61a2a689, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 199136 Jan 29 10:31 /usr/bin/grep
/usr/bin/grep: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f4564437ed282494b69a191fcb07a56235cce8ff, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 88440 Sep  5  2019 /usr/bin/stat
/usr/bin/stat: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=327cb96d448045d5b7a10dfcda6bd0282a3a8b41, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 27104 Jan 16 21:39 /usr/bin/file
/usr/bin/file: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=32715f59ea258e8fdf0dd8763fc501f958b0c4d6, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 320160 Feb 18 02:05 /usr/bin/find
/usr/bin/find: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b8b9756abacab10f704aec42954e3fd2292f1e85, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47480 Sep  5  2019 /usr/bin/head
/usr/bin/head: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ce008644d1531db879a7698fde5952af3b9d5951, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 137688 Feb 27 06:52 /usr/bin/ps
/usr/bin/ps: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=21b21cccacabfe9b0573bf0b894279a9502005b4, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 51544 Sep  5  2019 /usr/bin/readlink
/usr/bin/readlink: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=fd0a00264061ff768015704e147ee829e05d55c0, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 39256 Sep  5  2019 /usr/bin/basename
/usr/bin/basename: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d789f6a92a3ead8bb44badf3208926095d0c5b0b, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 47480 Sep  5  2019 /usr/bin/id
/usr/bin/id: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f8db9064d2203f35fa4c3c30f6ec4b0b7c614b5f, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 946 Dec  7  2019 /usr/bin/which
/usr/bin/which: POSIX shell script, ASCII text executable
-rwxr-xr-x 1 root root 548568 Jul 24  2019 /usr/bin/wget
/usr/bin/wget: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=844ac99e93a029c9bfc6b91a711f3f1084cc6e97, for GNU/Linux 3.2.0, stripped
-rwxr-xr-x 1 root root 239848 Jun 17 15:03 /usr/bin/curl
/usr/bin/curl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3e5ddff37bd567d28456f76805408eb82995fb9e, for GNU/Linux 3.2.0, stripped
lrwxrwxrwx 1 root root 24 Apr  7 13:42 /usr/bin/readelf -> x86_64-linux-gnu-readelf
-rwxr-xr-x 1 root root 658360 Apr  7 13:42 /usr/bin/x86_64-linux-gnu-readelf
/usr/bin/x86_64-linux-gnu-readelf: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=1d646833b5e3d41c50cad8e0c2c2bec6b0e4c4f6, for GNU/Linux 3.2.0, stripped
*** can not find command eu-readelf
~~~

## Command run to produce the error
`./checksec --file=zcat --output=json`
![Capture d’écran de 2020-06-30 21-20-25](https://user-images.githubusercontent.com/964610/86167854-8f3cf480-bb17-11ea-9695-858e11e55e9f.png)

file: [zcat.zip](https://github.com/slimm609/checksec.sh/files/4854008/zcat.zip)

expected output:
~~~JSON
{
  "zcat": {
    "relro": "no",
    "canary": "no",
    "nx": "no",
    "pie": "no",
    "rpath": "no",
    "runpath": "no",
    "symbols": "no",
    "fortify_source": "no",
    "fortified": "0",
    "fortify-able": "0"
  }
}

~~~

## OS version and Kernel version
OS: Ubuntu 20.04
kernel: 5.4.0-39-generic

## Debug output

Run the same command as above to reproduce the error but include the --debug flag

e.x  `checksec --debug -f /usr/bin/ls`
~~~
$ ./checksec --file=zcat --output=json --debug
{***function filecheck
***function filecheck->RELRO
 "file": { "relro":"no",
***function filecheck->canary
"canary":"no",
***function filecheck->nx
"nx":"no",
***function filecheck->pie
"pie":"no",
***function filecheck->rpath
"rpath":"no",
***function filecheck->runpath
"runpath":"no","symbols":"no",***function filecheck->fortify
"fortify_source":"no","fortified":"0","fortify-able":"0" } }
~~~

Thanks !

**Comment by slimm609** [comment]
Your version is an older version, this has already been fixed in a later version.   Please update and you should be good
```
checksec --file=systemd-notify --output=json | jq .
{
  "systemd-notify": {
    "relro": "full",
    "canary": "yes",
    "nx": "yes",
    "pie": "yes",
    "rpath": "no",
    "runpath": "yes",
    "symbols": "no",
    "fortify_source": "yes",
    "fortified": "2",
    "fortify-able": "2"
  }
}
```

**Comment by Wenzel** [comment]
Hi,

I just recloned the entire repo, and the issue is still there.
![Capture d’écran de 2020-07-19 16-25-01](https://user-images.githubusercontent.com/964610/87877068-7fa92100-c9dc-11ea-82f0-31869ae0ab0b.png)

**Comment by slimm609** [comment]
I will try and recreate the issue.  Can you run the docker-compose inside the repo and test in the container if you get the same issue.  As you see from my above post, it doesn’t have that issue.

**Comment by Wenzel** [comment]
@slimm609 thanks for reopening the issue.
I don't know docker-compose, just docker.

I built your Ubuntu image, and I have a repro inside the container:
![Capture d’écran de 2020-07-19 16-38-22](https://user-images.githubusercontent.com/964610/87877399-6608d900-c9de-11ea-96c9-3013dfe43c2b.png)

**Comment by slimm609** [comment]
should be fixed now in master.     If `relro` was `full` or `partial` then it was correct, if it was `no` then it would output file.
